### ISSUE TITLE
Import Modules from react-native

### ISSUE THREAD

**Issue by fab1an** [kriszyp/eslint-plugin-auto-import#1]
How do I configure this plugin so that if I already have:

`import { StyleSheet, Animated } from 'react-native';`

and use `View`, that it adds it to the import:

`import { StyleSheet, Animated, View } from 'react-native';`

Thank you.

**Comment by kriszyp** [comment]
This should be configured like:

```
"auto-import/auto-import": [2, {
      "packages": {
        "react-native": {
          "hasExports": "./node_modules/react-native"
        },
```

The path to your target module is computed relative to the parent of `node_modules`. It is essential that the module is node-loadable with exports visible to node.

I also added a new commit/tag that makes it possible to use a non-relative module reference, so you can use `hasExports: 'react-native'`, as long as `react-native` is a package/module in your node path module path (you can test with `require('react-native').View` in node).

**Comment by fab1an** [comment]
Ok, well it doesn't work for me. Might be because the `main` in react-native's `package.json` is rather complex: https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js

**Comment by fab1an** [comment]
Is there a way to tell your plugin explicitely that `View` is to be found in `react-native` and imported like this: `import { View } from react-native`. That would help a lot, since it's always the same things that I import over and over again…

**Comment by kriszyp** [comment]
You can certainly just create your own module that exports a set of properties, and then reference that in hasExports:

```
export.View = true
export.StyleSheet = true
export.Animated = true
```

I played around with trying to get react-native to load in node, but there doesn't seem to be any easy way to do it.

**Comment by fab1an** [comment]
Any news on this? I would love a config option where I could just statically define things to import, like that `View` is always in `react-native`.

**Comment by kriszyp** [comment]
Does the option above not work for you? I think it would be something like:
`.eslintrc`:

```
"auto-import/auto-import": [2, {
      "packages": {
        "react-native": {
          "hasExports": "react-exports"
```

`react-exports.js`:

```
export.View = true
...
```

Again, it looks like it react-native simply does not load in node, so a separate module describing the exports is necessary.

**Comment by fab1an** [comment]
That works, I didn't realize that "hasExports" needs a filename.

Now I only need to be able to use it with JSX.

**Comment by fab1an** [comment]
I'm closing this, since the "hasExports" workaround is fine for me.
